### ISSUE TITLE
SVG rendered differently in browsers

### ISSUE THREAD

**Issue by rugk** [PrivateBin/assets#3]
# PNG

![PrivateBin icon - Inkscape](https://raw.githubusercontent.com/PrivateBin/assets/f811093776bc07cc8453ecb12e11f6988589c4da/images/preview/icon.png)
### vs
# SVG

![PrivateBin icon - SVG](https://cdn.rawgit.com/PrivateBin/assets/f811093776bc07cc8453ecb12e11f6988589c4da/images/preview/icon.svg)

In my browser (Firefox 47.0.1) it looks very different.

As I have no idea why this happens and how to fix it so [I've asked on Stackexchange about this](https://graphicdesign.stackexchange.com/questions/74897/gradient-rendered-differently-in-inkscape-png-export-and-browser).

**Comment by elrido** [comment]
Its not just affecting Browsers, it has the same issue in Ubuntus SVG preview in the file browser.

In 6e04def I pushed a patch that allows a non Inkscape renderer to display the radial gradient. I would guess that the problem is, that not all renderers understand how to render the gradient with units instead of percentages. Here is the changed section:

```
<radialGradient
   inkscape:collect="always"
   xlink:href="#linearGradient7636"
   id="radialGradient7642"
   cx="50%"
   cy="50%"
   fx="50%"
   fy="50%"
   r="40%"
   spreadMethod="pad" />
```

And this is how it looks in my Browser now:

![example](https://cloud.githubusercontent.com/assets/1017622/16940604/60e988b2-4d8b-11e6-8273-3fc24c580cad.png)

You might want to improve on it by playing around with the `r` attribute for the radius.

**Comment by rugk** [comment]
Awesome! It works in my browser too. And I think the radius is all right...

I just hope Inkscape edits it correctly and does not revert these changes when saved. I'll try it out...

**Comment by rugk** [comment]
So unfortunately no. Even when the object is just moved, the values are replaced. I have opened [ a bug report on Inkscape](https://bugs.launchpad.net/inkscape/+bug/1604276), so let's see what they say.

As for this issue, it seems to be fixed.
